accounts/urls.py
from django.urls import path,reverse_lazy
from . import views
from django.contrib.auth import views as imp_views

app_name = 'accounts'

urlpatterns = [
    path("login/",imp_views.LoginView.as_view(template_name='registrations/login.html'),name='login'),
    path("logout/",imp_views.LogoutView.as_view(),name='logout'),
    path("register/",views.register.as_view(),name='signup'),
    path("password-reset/",imp_views.PasswordResetView.as_view(template_name='registrations/password_reset_form.html',
                                                                email_template_name='registrations/password_reset_email.html',
                                                                subject_template_name='registrations/password_reset_subject.txt',
                                                                from_email="mohammedfarhan045@gmail.com",
                                                                success_url =reverse_lazy('accounts:password_reset_done')),name='password_reset'),
    path("password-reset/done/",imp_views.PasswordResetDoneView.as_view(template_name='registrations/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', imp_views.PasswordResetConfirmView.as_view(template_name='registrations/password_reset_confirm.html',
                                                                                success_url=reverse_lazy("accounts:password_reset_complete")), name='password_reset_confirm'),
    path("password-reset/complete/",imp_views.PasswordResetCompleteView.as_view(template_name='registrations/password_reset_complete.html'),name='password_reset_complete'),
    path("All-users/",views.Allusers,name="all_users"),
]

blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog' 

urlpatterns = [
    path("",views.PostList.as_view(),name='home'),
    path("create-profile/",views.profile.as_view(),name="profile_create"),
    path("profile_page/<username>/",views.profile_page,name="profile_page"),
    path("profile-update/<username>/<pk>/",views.update_profile.as_view(),name='profile_update'),
    path("create-post/",views.postcreate.as_view(),name='create_post'),
    path("post-detail/<slug>/",views.postdetail.as_view(),name='post_detail'),
    path("like-post/<pk>/",views.likeview,name="post_like"),
    path("post-update/<slug>/<pk>/",views.postUpdate.as_view(),name='post_update'),
    path("post-delete/<slug>/<pk>/",views.postDelete.as_view(),name="post_delete"),
    path("post-detail/<slug>/comment/",views.CommentCreate.as_view(),name="create_comment"),
    path("delete-comment/<slug>/<pk>/",views.CommentDelete.as_view(),name="comment_delete"),
    path("follow/<pk>",views.follow_user,name="follow")
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL ,document_root= settings.MEDIA_ROOT)

legit_bouys/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('blog.urls','blog'),namespace='blog')),
    path("accounts/",include(('accounts.urls','accounts'),namespace='accounts')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
]

blog/models.py
# from blog.views import profile
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
import datetime
from ckeditor.fields import RichTextField 
from django.utils.text import slugify
from .utils import modelsnippet
from hitcount.models import HitCount,HitCountMixin
from django.contrib.contenttypes.fields import GenericRelation
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,null=True,blank=True,on_delete=models.SET_NULL)
    profilepic = models.ImageField(upload_to='images/profile_pics/',default='images/profile_pics/default.png')
    bio = models.TextField()
    website_url = models.URLField(null=True,blank=True)
    facebook_url = models.URLField(null=True,blank=True)
    instagram_url = models.URLField(null=True,blank=True)
    twitter_url = models.URLField(null=True,blank=True)
    pintrest_url = models.URLField(null=True,blank=True)
    follow = models.ManyToManyField(User,blank=True,related_name="follows")

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse("blog:home")

    @property
    def total_followers(self):
        return self.follow.count()

    @property
    def follower_names(self):
        follower_list = []
        for a in self.follow.all():
            follower_list.append(a)
        return follower_list
        # return " , ".join(a.username for a in self.follow.all())

    @receiver(post_save,sender=User)
    def create_profile(sender,instance,created,**kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save,sender=User)
    def update_profile(sender,instance,created,**kwargs):
        if created == False:
            instance.userprofile.save()
            


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    category = models.CharField(max_length=50)
    created_date = models.DateTimeField(auto_now=True)
    body = RichTextField()
    auther = models.ForeignKey(User,on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to = 'images/post_thumbnails/',null=True,blank=True)
    snippet = models.TextField(max_length=255)
    like = models.ManyToManyField(User,related_name='blog_posts')
    # views = models.IntegerField(default=0)
    Hit_count_generic = GenericRelation(HitCount,object_id_field='object_pk',related_query_name='hit_count_generic_relation')


    @property
    def get_likes(self):
        return self.like.count()

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        self.snippet = modelsnippet(self.body)
        return super().save(*args,**kwargs)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:home")

    class Meta:
        ordering = ["-created_date"]

class Comments(models.Model):
    User = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey('Post',on_delete=models.CASCADE,related_name='comments')
    time = models.DateTimeField(auto_now=True)
    message = models.TextField()

    def __str__(self):
        return str((self.post.title) + "  -- @" + self.User.username)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'slug':self.post.slug})

    class Meta:
        ordering = ["-time"]

blog/forms.py
from django import forms
from .models import UserProfile,Post,Comments

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("bio","profilepic","website_url","facebook_url","instagram_url","twitter_url","pintrest_url")

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['bio'].label = "Bio"
        self.fields['profilepic'].label = "Profile Picture"
        self.fields["website_url"].label = "Website link (optional)"
        self.fields["facebook_url"].label = "Facebook (optional) "
        self.fields["instagram_url"].label = "Instagram (Optional) "
        self.fields["twitter_url"].label = "Twitter (Optional) "
        self.fields["pintrest_url"].label = "Pintrest (Optional)"

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title","category","thumbnail","body")

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields["title"].label = "Blog Title"
        self.fields["category"].label = "Category"
        self.fields["thumbnail"].label = "Blog Thumbnail"
        self.fields["body"].label = "Content"

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("thumbnail","body")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ("message",)

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            self.fields["message"].label = "Comment"

blog/views.py
from django.shortcuts import render,get_object_or_404,reverse
from django.views.generic import CreateView,UpdateView,ListView,DeleteView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionDenied
from .models import UserProfile,Post,Comments
from django.contrib.auth.models import User
from .forms import UserProfileForm,PostCreateForm,PostUpdateForm,CommentForm
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from hitcount.views import HitCountDetailView
from django.contrib.auth.decorators import login_required

class PostList(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'

    def get_context_data(self,*args,**kwargs):
        data = super().get_context_data(*args,**kwargs)
        # data['snippet'] = homeSnippet()
        return data

class profile(CreateView,LoginRequiredMixin):
    model = UserProfile
    template_name = 'blog/profile_create.html'
    form_class = UserProfileForm

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

def profile_page(request,username):
    user_profile = get_object_or_404(User,username=username)
    user_posts = Post.objects.filter(auther__username__iexact=username)
    user_follow = False
    if user_profile.userprofile.follow.filter(id=request.user.id).exists():
        user_follow = True
    return render(request,'blog/profile_page.html',{"user_profile":user_profile,'user_posts':user_posts,'user_follow':user_follow})

class update_profile(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'blog/profile_create.html'

    def get_object(self,*args,**kwargs):
        obj = super().get_object(*args,**kwargs)
        if obj.user != self.request.user:
            raise PermissionDenied()
        return obj

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class postcreate(CreateView,LoginRequiredMixin):
    model = Post
    form_class = PostCreateForm
    template_name = 'blog/post_create.html'

    def form_valid(self,form):
        form.instance.auther = self.request.user
        form.instance.created_date = datetime.datetime.now()
        return super().form_valid(form)

class postdetail(HitCountDetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail2.html'
    count_hit = True

    def get_context_data(self,*args,**kwargs):
        data = super().get_context_data(*args,**kwargs)
        post = get_object_or_404(Post,slug=self.kwargs['slug'])
        liked = False
        if post.like.filter(id=self.request.user.id).exists():
            liked = True
        
        data['all_posts'] = Post.objects.all
        data['liked'] = liked
        data["comments"] = Comments.objects.filter(post=post)
        return data


@login_required
def likeview(request,pk):
    post = get_object_or_404(Post,id=pk)
    liked = False
    if post.like.filter(id=request.user.id).exists():
        post.like.remove(request.user)
        liked = False
    else:
        post.like.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('blog:post_detail', kwargs={'slug':post.slug} ))

class postUpdate(UpdateView,LoginRequiredMixin):
    model = Post
    form_class = PostUpdateForm
    template_name = 'blog/post_update.html'

    def get_object(self,*args,**kwargs):
        obj = super().get_object(*args,**kwargs)
        if obj.auther != self.request.user:
            raise PermissionDenied()
        return obj

class postDelete(DeleteView,LoginRequiredMixin):
    model = Post
    template_name = 'blog/post_delete_confirm.html'
    success_url = reverse_lazy("blog:home")

    def get_object(self,*args,**kwargs):
        obj = super().get_object(*args,**kwargs)
        if obj.auther != self.request.user:
            raise PermissionDenied()
        return obj

class CommentCreate(CreateView,LoginRequiredMixin):
    model = Comments
    form_class = CommentForm
    
    def form_valid(self,form,**kwargs):
        post = get_object_or_404(Post,slug=self.kwargs['slug'])
        form.instance.User = self.request.user
        form.instance.time = datetime.datetime.now()
        form.instance.post = post
        form.save()
        return super().form_valid(form,**kwargs)
    
class CommentDelete(DeleteView,LoginRequiredMixin):
    model = Comments
    
    def get_object(self,*args,**kwargs):
        obj = super().get_object(*args,**kwargs)
        if obj.User != self.request.user:
            raise PermissionDenied()
        return obj

@login_required
def follow_user(request,pk):
    profile = get_object_or_404(UserProfile,id=pk)
    if profile.follow.filter(id=request.user.id).exists():
        profile.follow.remove(request.user)
    else:
        profile.follow.add(request.user)
    return HttpResponseRedirect(reverse("blog:profile_page",kwargs={'username':profile.user.username}))

blog/templates/main.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Legit Bouys</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel='stylesheet' href='{% static "css/woocommerce-layout.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' href='{% static "css/woocommerce-smallscreen.css" %}' type='text/css' media='only screen and (max-width: 768px)'/>
    <link rel='stylesheet' href='{% static "css/woocommerce.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' href='{% static "css/font-awesome.min.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' href='{% static "style.css" %}' type='text/css' media='all'/>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Oswald:400,500,700%7CRoboto:400,500,700%7CHerr+Von+Muellerhoff:400,500,700%7CQuattrocento+Sans:400,500,700' type='text/css' media='all'/>
    <link rel='stylesheet' href='{% static "css/easy-responsive-shortcodes.css" %}' type='text/css' media='all'/>

  </head>
  <body class="blog">
    <div id="page">
        <div class="container">
            <header id="masthead" class="site-header">
            <div class="site-branding">
                <h1 class="site-title"><a href="{% url 'blog:home' %}" rel="home">Legit Bouys</a></h1>
                <h2 class="site-description">A Simple website to Blog</h2>
            </div>
            <nav id="site-navigation" class="main-navigation">
            <button class="menu-toggle">Menu</button>
            <a class="skip-link screen-reader-text" href="#content">Skip to content</a>
            <div class="menu-menu-1-container">
                <ul id="menu-menu-1" class="menu">
                    <li><a href="{% url 'blog:home' %}">Blog</a></li>
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'blog:create_post' %}">New post</a></li>
                      <li><a href="{% url 'accounts:all_users' %}">All Users</a></li>
                      <li><a ></a>Welcome {{user.username}}</li>   
                      <li><a href="#"> <img style="width: 50px;height:50px;border-radius:50px;float:right;margin-right:0px;" src="{{user.userprofile.profilepic.url}}" alt=""> </a>
                      <ul class="sub-menu">
                          <li><a href="{% url 'blog:profile_page' user.username %}">Profile</a></li>
                          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                      </ul>
                        
                    {% else %}
                        <li><a href="{% url 'accounts:signup' %}">Create profile</a></li>
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
            </nav>
            </header>

    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

   

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script src='{% static "js/jquery.js" %}'></script>
    <script src='{% static "js/plugins.js" %}'></script>
    <script src='{% static "js/scripts.js" %}'></script>
    <script src='{% static "js/masonry.pkgd.min.js" %}'></script>
  </body>
</html>

blog/templates/main2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Legit Bouys - Blog </title>
  <meta content="A multi user blogging Platform" name="description">
  <meta content="Blog" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon-1.png' %}" rel="icon">
  <link href="{% static 'assets/img/favicon-1.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: BizLand - v1.2.1
  * Template URL: https://bootstrapmade.com/bizland-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <!-- <div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
    <div class="container d-flex">
      <div class="contact-info mr-auto">
        <i class="icofont-envelope"></i> <a href="mailto:contact@example.com">contact@example.com</a>
        <i class="icofont-phone"></i> +1 5589 55488 55
      </div>
      <div class="social-links">
        <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
        <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
        <a href="#" class="skype"><i class="icofont-skype"></i></a>
        <a href="#" class="linkedin"><i class="icofont-linkedin"></i></i></a>
      </div>
    </div id="topbar">
  </div> id="header" class="fixed-top"  -->

  <!-- ======= Header ======= -->
  <header class="navbar navbar-expand-lg navbar-light bg-light" >
    <div class="container-fluid" >

      <!-- <h1 class="logo mr-auto"><a href="index.html">Legit Bouys<span></span></a></h1> -->
      <!-- Uncomment below if you prefer to use an image logo -->
      <a href="{% url 'blog:home' %}" class="navbar-brand"><img src="{% static 'assets/img/favicon-1.png' %}" style="max-height: 100px;max-width:100px;"></a>

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li ><a href="{% url 'blog:home' %}">Home</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'blog:create_post' %}">New post</a></li>
            <li><a href="{% url 'accounts:all_users' %}">All Users</a></li>
            <li><a ></a>Welcome {{user.username}}</li>   
            <li class="drop-down"><a href=""><img src="{{user.userprofile.profilepic.url}}" style="width: 50px;height:50px;border-radius:50px;"></a>
              <ul>
                <li><a href="{% url 'blog:profile_page' user.username %}">Profile</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
              </ul>
            </li>
          {% else %}  
            <li><a href="{% url 'accounts:signup' %}"><button class="btn btn-outline-success me-2" type="button">Sign Up</button></a></li>
            <li><a href="{% url 'accounts:login' %}"><button class="btn btn-outline-success me-2" type="button">Login</button></a></li>
          {% endif %}

        </ul>
      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->

  <div class="container">
    <div style="margin: 70px 0px ;">
      {% block content %}
    
      {% endblock %}
    </div>
  </div>
  

  <div id="preloader"></div>
  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>