accounts/urls.py
from django.urls import path,reverse_lazy
from . import views
from django.contrib.auth import views as imp_views

app_name = 'accounts'

urlpatterns = [
    path("login/",imp_views.LoginView.as_view(template_name='registrations/login.html'),name='login'),
    path("logout/",imp_views.LogoutView.as_view(),name='logout'),
    path("register/",views.register.as_view(),name='signup'),
    path("password-reset/",imp_views.PasswordResetView.as_view(template_name='registrations/password_reset_form.html',
                                                                email_template_name='registrations/password_reset_email.html',
                                                                subject_template_name='registrations/password_reset_subject.txt',
                                                                from_email="mohammedfarhan045@gmail.com",
                                                                success_url =reverse_lazy('accounts:password_reset_done')),name='password_reset'),
    path("password-reset/done/",imp_views.PasswordResetDoneView.as_view(template_name='registrations/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', imp_views.PasswordResetConfirmView.as_view(template_name='registrations/password_reset_confirm.html',
                                                                                success_url=reverse_lazy("accounts:password_reset_complete")), name='password_reset_confirm'),
    path("password-reset/complete/",imp_views.PasswordResetCompleteView.as_view(template_name='registrations/password_reset_complete.html'),name='password_reset_complete'),
    path("All-users/",views.Allusers,name="all_users"),
]

blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog' 

urlpatterns = [
    path("",views.PostList.as_view(),name='home'),
    path("create-profile/",views.profile.as_view(),name="profile_create"),
    path("profile_page/<username>/",views.profile_page,name="profile_page"),
    path("profile-update/<username>/<pk>/",views.update_profile.as_view(),name='profile_update'),
    path("create-post/",views.postcreate.as_view(),name='create_post'),
    path("post-detail/<slug>/",views.postdetail.as_view(),name='post_detail'),
    path("like-post/<pk>/",views.likeview,name="post_like"),
    path("post-update/<slug>/<pk>/",views.postUpdate.as_view(),name='post_update'),
    path("post-delete/<slug>/<pk>/",views.postDelete.as_view(),name="post_delete"),
    path("post-detail/<slug>/comment/",views.CommentCreate.as_view(),name="create_comment"),
    path("delete-comment/<slug>/<pk>/",views.CommentDelete.as_view(),name="comment_delete"),
    path("follow/<pk>",views.follow_user,name="follow")
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL ,document_root= settings.MEDIA_ROOT)

legit_bouys/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('blog.urls','blog'),namespace='blog')),
    path("accounts/",include(('accounts.urls','accounts'),namespace='accounts')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
]

blog/models.py
# from blog.views import profile
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
import datetime
from ckeditor.fields import RichTextField 
from django.utils.text import slugify
from .utils import modelsnippet
from hitcount.models import HitCount,HitCountMixin
from django.contrib.contenttypes.fields import GenericRelation
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,null=True,blank=True,on_delete=models.SET_NULL)
    profilepic = models.ImageField(upload_to='images/profile_pics/',default='images/profile_pics/default.png')
    bio = models.TextField()
    website_url = models.URLField(null=True,blank=True)
    facebook_url = models.URLField(null=True,blank=True)
    instagram_url = models.URLField(null=True,blank=True)
    twitter_url = models.URLField(null=True,blank=True)
    pintrest_url = models.URLField(null=True,blank=True)
    follow = models.ManyToManyField(User,blank=True,related_name="follows")

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse("blog:home")

    @property
    def total_followers(self):
        return self.follow.count()

    @property
    def follower_names(self):
        follower_list = []
        for a in self.follow.all():
            follower_list.append(a)
        return follower_list
        # return " , ".join(a.username for a in self.follow.all())

    @receiver(post_save,sender=User)
    def create_profile(sender,instance,created,**kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save,sender=User)
    def update_profile(sender,instance,created,**kwargs):
        if created == False:
            instance.userprofile.save()
            


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    category = models.CharField(max_length=50)
    created_date = models.DateTimeField(auto_now=True)
    body = RichTextField()
    auther = models.ForeignKey(User,on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to = 'images/post_thumbnails/',null=True,blank=True)
    snippet = models.TextField(max_length=255)
    like = models.ManyToManyField(User,related_name='blog_posts')
    # views = models.IntegerField(default=0)
    Hit_count_generic = GenericRelation(HitCount,object_id_field='object_pk',related_query_name='hit_count_generic_relation')


    @property
    def get_likes(self):
        return self.like.count()

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        self.snippet = modelsnippet(self.body)
        return super().save(*args,**kwargs)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:home")

    class Meta:
        ordering = ["-created_date"]

class Comments(models.Model):
    User = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey('Post',on_delete=models.CASCADE,related_name='comments')
    time = models.DateTimeField(auto_now=True)
    message = models.TextField()

    def __str__(self):
        return str((self.post.title) + "  -- @" + self.User.username)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'slug':self.post.slug})

    class Meta:
        ordering = ["-time"]

blog/forms.py
from django import forms
from .models import UserProfile,Post,Comments

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("bio","profilepic","website_url","facebook_url","instagram_url","twitter_url","pintrest_url")

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['bio'].label = "Bio"
        self.fields['profilepic'].label = "Profile Picture"
        self.fields["website_url"].label = "Website link (optional)"
        self.fields["facebook_url"].label = "Facebook (optional) "
        self.fields["instagram_url"].label = "Instagram (Optional) "
        self.fields["twitter_url"].label = "Twitter (Optional) "
        self.fields["pintrest_url"].label = "Pintrest (Optional)"

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title","category","thumbnail","body")

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields["title"].label = "Blog Title"
        self.fields["category"].label = "Category"
        self.fields["thumbnail"].label = "Blog Thumbnail"
        self.fields["body"].label = "Content"

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("thumbnail","body")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ("message",)

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            self.fields["message"].label = "Comment"

blog/views.py
from django.shortcuts import render,get_object_or_404,reverse
from django.views.generic import CreateView,UpdateView,ListView,DeleteView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionDenied
from .models import UserProfile,Post,Comments
from django.contrib.auth.models import User
from .forms import UserProfileForm,PostCreateForm,PostUpdateForm,CommentForm
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from hitcount.views import HitCountDetailView
from django.contrib.auth.decorators import login_required

class PostList(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'

    def get_context_data(self,*args,**kwargs):
        data = super().get_context_data(*args,**kwargs)
        # data['snippet'] = homeSnippet()
        return data

class profile(CreateView,LoginRequiredMixin):
    model = UserProfile
    template_name = 'blog/profile_create.html'
    form_class = UserProfileForm

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

def profile_page(request,username):
    user_profile = get_object_or_404(User,username=username)
    user_posts = Post.objects.filter(auther__username__iexact=username)
    user_follow = False
    if user_profile.userprofile.follow.filter(id=request.user.id).exists():
        user_follow = True
    return render(request,'blog/profile_page.html',{"user_profile":user_profile,'user_posts':user_posts,'user_follow':user_follow})

class update_profile(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'blog/profile_create.html'

    def get_object(self,*args,**kwargs):
        obj = super().get_object(*args,**kwargs)
        if obj.user != self.request.user:
            raise PermissionDenied()
        return obj

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class postcreate(CreateView,LoginRequiredMixin):
    model = Post
    form_class = PostCreateForm
    template_name = 'blog/post_create.html'

    def form_valid(self,form):
        form.instance.auther = self.request.user
        form.instance.created_date = datetime.datetime.now()
        return super().form_valid(form)

class postdetail(HitCountDetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail2.html'
    count_hit = True

    def get_context_data(self,*args,**kwargs):
        data = super().get_context_data(*args,**kwargs)
        post = get_object_or_404(Post,slug=self.kwargs['slug'])
        liked = False
        if post.like.filter(id=self.request.user.id).exists():
            liked = True
        
        data['all_posts'] = Post.objects.all
        data['liked'] = liked
        data["comments"] = Comments.objects.filter(post=post)
        return data


@login_required
def likeview(request,pk):
    post = get_object_or_404(Post,id=pk)
    liked = False
    if post.like.filter(id=request.user.id).exists():
        post.like.remove(request.user)
        liked = False
    else:
        post.like.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('blog:post_detail', kwargs={'slug':post.slug} ))

class postUpdate(UpdateView,LoginRequiredMixin):
    model = Post
    form_class = PostUpdateForm
    template_name = 'blog/post_update.html'

    def get_object(self,*args,**kwargs):
        obj = super().get_object(*args,**kwargs)
        if obj.auther != self.request.user:
            raise PermissionDenied()
        return obj

class postDelete(DeleteView,LoginRequiredMixin):
    model = Post
    template_name = 'blog/post_delete_confirm.html'
    success_url = reverse_lazy("blog:home")

    def get_object(self,*args,**kwargs):
        obj = super().get_object(*args,**kwargs)
        if obj.auther != self.request.user:
            raise PermissionDenied()
        return obj

class CommentCreate(CreateView,LoginRequiredMixin):
    model = Comments
    form_class = CommentForm
    
    def form_valid(self,form,**kwargs):
        post = get_object_or_404(Post,slug=self.kwargs['slug'])
        form.instance.User = self.request.user
        form.instance.time = datetime.datetime.now()
        form.instance.post = post
        form.save()
        return super().form_valid(form,**kwargs)
    
class CommentDelete(DeleteView,LoginRequiredMixin):
    model = Comments
    
    def get_object(self,*args,**kwargs):
        obj = super().get_object(*args,**kwargs)
        if obj.User != self.request.user:
            raise PermissionDenied()
        return obj

@login_required
def follow_user(request,pk):
    profile = get_object_or_404(UserProfile,id=pk)
    if profile.follow.filter(id=request.user.id).exists():
        profile.follow.remove(request.user)
    else:
        profile.follow.add(request.user)
    return HttpResponseRedirect(reverse("blog:profile_page",kwargs={'username':profile.user.username}))

blog/templates/blog/post_detail.html
{% extends 'main2.html' %}
{% load static %}
{% load hitcount_tags %}
{% load bootstrap4 %}

{% block content %}

    <!-- <style>
        .entry-content
    </style>     -->

    <div id="content" class="site-content">
        <div id="primary" class="content-area column two-thirds">
            <main id="main" class="site-main" role="main">
            <article>
                <header class="entry-header">
                    <h1 class="entry-title">{{post.title}}</h1>
                    <div class="entry-meta">
                            <span class="posted-on"><time class="entry-date published">{{post.created_date}}</time></span>						
                            <span class="comments-link"><a href="#comments">Leave a comment</a></span>
                            <span><p>Page Views : {% get_hit_count for post %}</p></span>
                        </div>
                    <!-- {% if post.thumbnail %}
                        <div class="entry-thumbnail">					
                            <img src="{{post.thumbnail.url}}" alt="">
                        </div>
                    {% endif %} -->
                </header>
            <!-- .entry-header -->
                <div class="entry-content img-fluid">
                    {{post.body|safe}}
                    <span><p>likes - {{post.get_likes}}</p></span>
                </div>
                
                {% if user.is_authenticated %}
                    {% if user.username == post.auther.username %}
                        <a href="{% url 'blog:post_update' post.slug post.pk  %}" class="btn btn-primary">Update Post </a>
                    {% endif %}
                {% endif %}
                <!-- .entry-content -->
                <footer class="entry-footer">
                    <form action="{% url 'blog:post_like' post.pk %}" method="post">
                        {% csrf_token %}
                        {% if liked %}
                            <button type="submit" style="background: none;border:none" ><img src="{% static 'images/liked.png' %}" style="max-height: 75px;max-width:75px;" ></button>
                        {% else %}
                            <button type="submit" style="background: none;border:none" ><img src="{% static 'images/like.png' %}" style="max-height: 75px;max-width:75px" ></button>
                            <p>like</p>
                        {% endif %}
                    </form>
                    <div>
                        <br><br>
                        {% if user.is_authenticated %}
                            <h3>Add Comment</h3>
                            <form action="{% url 'blog:create_comment' post.slug %}" method="post">
                                {% csrf_token %}
                                <label for="message">Message</label>
                                <!-- <input type="textarea" name="message"> -->
                                <textarea name="message" id="" cols="30" rows="5"></textarea>
                                <input type="submit" value="Post Comment">
                            </form>
                        {% else %}
                            <br><br>
                            <p>Please <a href="{% url 'accounts:login' %}">Login</a> to add comment</p>
                        {% endif %}
                    </div>
                </footer>
                <!-- .entry-footer -->
            </article>
            <!-- #post-## -->
            <!-- <nav class="navigation post-navigation" role="navigation">
                <h1 class="screen-reader-text">Post navigation</h1>
                <div class="nav-links"> -->
                    <br><br>
                    <div class="nav-previous">
                        <a href="{% url 'blog:home' %}" rel="prev"><span class="meta-nav">←</span> Thanks for watching!</a>
                    </div>
                    <br>
                <!-- </div>
                .nav-links
            </nav> -->
            <!-- .navigation -->
            <div id="comments" class="comments-area">
                <div>
                    <h3>Comments</h3>
                    {% if comments %}
                        {% for comment in comments %}
                        <div class="card ">
                            <div class="card-body">
                            <p class="card-text">{{comment.message}}</p>
                            <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                            </div>
                            <div class="card-footer text-muted">
                                <p>By @{{comment.User.username}} | On {{comment.time}}</p>
                            </div>
                        </div>
                        <br><br>
                        {% endfor %}
                    {% else %}
                        <div class="card">
                            <div class="card-body">
                                <p class="card-text">There are no comments on this post</p>   
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            <!-- #comments -->
            </main>
            <!-- #main -->
        </div>
        <div id="secondary" class="column third">
            <div id="sidebar-1" class="widget-area" role="complementary">
                <aside id="text-7" class="widget widget_text">
                <h4 class="widget-title">Follow Author</h4>
                {% if post.auther.userprofile.website_url %}
                    <a href="{{post.auther.userprofile.website_url}}"><img src="{% static 'images/website.png' %}" style="max-height: 50px;max-width:50px"></a>
                {% endif %}

                {% if post.auther.userprofile.facebook_url %}
                    <a href="{{post.auther.userprofile.facebook_url}}"><img src="{% static 'images/facebook_icon.png' %}" style="max-height: 50px;max-width:50px"></a>
                {% endif %}

                {% if post.auther.userprofile.instagram_url %}
                    <a href="{{post.auther.userprofile.instagram_url}}"><img src="{% static 'images/instagram.png' %}" style="max-height: 50px;max-width:50px"></a>
                {% endif %}

                {% if post.auther.userprofile.twitter_url %}
                    <a href="{{post.auther.userprofile.twitter_url}}"><img src="{% static 'images/twitter.png' %}" style="max-height: 50px;max-width:50px"></a>
                {% endif %}

                {% if post.auther.userprofile.pintrest_url %}
                    <a href="{{post.auther.userprofile.pintrest_url}}"><img src="{% static 'images/pinterest.png' %}" style="max-height: 50px;max-width:50px"></a>
                {% endif %}
                <br><br>
                </aside>
            </div>
            <!-- .widget-area -->
            <div class="card mb-3" style="max-width: 540px;">
                <div class="card-header">About Author</div>
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src="{{post.auther.userprofile.profilepic.url}}" class="img-fluid">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">{{post.auther.first_name}} {{post.auther.last_name}}</h5>
                      <p class="card-text">{{post.auther.userprofile.bio}}</p>
                      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>
                  </div>
                </div>
            </div>
        </div>
        <!-- #secondary -->
    </div>
    <!-- #content -->

    <script>
    
        /*document.getElementById("del_confirm").style.display = "none";*/
        function myfunction() {
            document.getElementById("del_confirm").style.display = "block";
        }

        body_img = document.getElementsByClassName("entry-content p img");
        body_img.classList.add("img-fluid")
        
    </script>
{% endblock %}

blog/templates/blog/post_detail2.html
{% extends 'main2.html' %}
{% load static %}
{% load hitcount_tags %}
{% load bootstrap4 %}

{% block content %}

    <style>
        .ck-editor__editable {
            max-height: 400px;
            max-width: 600px;
        }
    </style>    

    <div class="row">
        <div class="col-sm-8">
            <div class="card ">
                <div class="card-body">
                    <h3 class="card-title">{{post.title}}</h3>
                    <span><a class="text-muted">{{post.created_date}}</a></span>
                    <br>
                    <span class="cat-links">
                        <a  rel="category tag">Page Views: {% get_hit_count for post %} | </a> <a  rel="category tag">comments : {{post.comments.count}} | </a> <a  rel="category tag">likes : {{post.get_likes}}</a>
                    </span>
                    <br><br><br><br>
                    <p class="card-text"id="body-img">{{post.body|safe}}</p>
                    <form action="{% url 'blog:post_like' post.pk %}" method="post">
                        {% csrf_token %}
                        {% if liked %}
                            <button type="submit" style="background: none;border:none" ><img src="{% static 'images/liked.png' %}" style="max-height: 75px;max-width:75px;" ></button>
                        {% else %}
                            <button type="submit" style="background: none;border:none" ><img src="{% static 'images/like.png' %}" style="max-height: 75px;max-width:75px" ></button>
                            <p>like</p>
                        {% endif %}
                    </form>
                    <br>
                    <div class="nav-previous">
                        <a href="{% url 'blog:home' %}" rel="prev"><span class="meta-nav">←</span> Thanks for Reading!</a>
                    </div>
                </div>
            </div>
                    
            <br><br>    
                <div>
                    {% if user.is_authenticated %}
                        <h3>Add Comment</h3>
                        <form action="{% url 'blog:create_comment' post.slug %}" method="post">
                            {% csrf_token %}
                            <label for="message">Message</label>
                            <!-- <input type="textarea" name="message"> -->
                            <textarea name="message" id="" cols="30" rows="5"></textarea>
                            <input type="submit" value="Post Comment">
                        </form>
                    {% else %}
                        <br>
                        <p>Please <a href="{% url 'accounts:login' %}">Login</a> to add comment</p>
                    {% endif %}
                    
                    <br><br>

                    <h5>Comments ({{post.comments.count}}) </h5>
                    {% if comments %}
                        {% for comment in comments %}
                        <div class="card ">
                            <div class="card-body">
                            <p class="card-text">{{comment.message}}</p>
                            <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
                            </div>
                            <div class="card-footer text-muted">
                                <p>By @{{comment.User.username}} | On {{comment.time}}</p>
                            </div>
                        </div>
                        <br><br>
                        {% endfor %}
                    {% else %}
                        <div class="card">
                            <div class="card-body">
                                <p class="card-text">There are no comments on this post</p>   
                            </div>
                        </div>
                    {% endif %}
                </div>
            
              
        </div>
        <div class="col-sm-4">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="card-header">About Author</div>
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src="{{post.auther.userprofile.profilepic.url}}" class="img-fluid">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">{{post.auther.first_name}} {{post.auther.last_name}}</h5>
                      <p class="card-text">{{post.auther.userprofile.bio}}</p>
                      <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                    </div>
                  </div>
                </div>
            </div>

            <div class="card mb-3" style="max-width: 540px;">
                
                <div class="row g-0">
                    <div class="card-body">
                      <h5 class="card-title">Follow Auther</h5>
                      <p class="card-text">
                            {% if post.auther.userprofile.website_url %}
                                <a href="{{post.auther.userprofile.website_url}}"><img src="{% static 'images/website.png' %}" style="max-height: 50px;max-width:50px"></a>
                            {% endif %}
            
                            {% if post.auther.userprofile.facebook_url %}
                                <a href="{{post.auther.userprofile.facebook_url}}"><img src="{% static 'images/facebook_icon.png' %}" style="max-height: 50px;max-width:50px"></a>
                            {% endif %}
            
                            {% if post.auther.userprofile.instagram_url %}
                                <a href="{{post.auther.userprofile.instagram_url}}"><img src="{% static 'images/instagram.png' %}" style="max-height: 50px;max-width:50px"></a>
                            {% endif %}
            
                            {% if post.auther.userprofile.twitter_url %}
                                <a href="{{post.auther.userprofile.twitter_url}}"><img src="{% static 'images/twitter.png' %}" style="max-height: 50px;max-width:50px"></a>
                            {% endif %}
            
                            {% if post.auther.userprofile.pintrest_url %}
                                <a href="{{post.auther.userprofile.pintrest_url}}"><img src="{% static 'images/pinterest.png' %}" style="max-height: 50px;max-width:50px"></a>
                            {% endif %}
                        </p>                      
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function myFunction() {
            var x = document.getElementById("body-img").querySelectorAll("img");
            var i;
            for (i = 0; i < x.length; i++) {
              x[i].style.maxHeight = "400px";
              x[i].style.maxWidth = "600px"
            }
        }
        myFunction();
    </script>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'main2.html' %}
{% load hitcount_tags %}


{% block content %}
    {% if user.is_authenticated %}
        <div class="d-block d-sm-none">
            <div class="row">
                <div class="col">
                    <a href="{% url 'blog:profile_page' user.username  %}"></a><img src="{{user.userprofile.profilepic.url}}" style="max-height: 75px;max-width:75px;border-radius:50%;">
                    <h5 class="text-muted">Welcome <a href="{% url 'blog:profile_page' user.username  %}">@{{user.username}}</a></h5>
                </div>
                <!-- <div class="col">
                    <h5 class="text-muted">Welcome @{{user.username}}</h5>
                    
                </div> -->
            </div>
            
        </div>
    {% endif %}
    <br><br>
    {% for post in posts %}
        <div class="card bg-light mb-3" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
            <div class="card-header bg-transparent border-success">
                <h5>Author : <a href="{% url 'blog:profile_page' post.auther.username  %}">@{{post.auther.username}}</a></h5>
                <span class="cat-links">
                    <a  rel="category tag">Views: {% get_hit_count for post %} | </a> <a  rel="category tag">comments : {{post.comments.count}} | </a> <a  rel="category tag">likes : {{post.get_likes}}</a>
                </span>    
            </div>
            <div class="card-body">
                <h2 class="card-title"><a href="{% url 'blog:post_detail' post.slug  %}">{{post.title}}</a></h2>
                <p class="card-text">{{post.snippet|safe}} <br> <a href="{% url 'blog:post_detail' post.slug  %}" class="btn-link">Continue Reading</a> </p>
                {% if post.thumbnail %}
                    <img src="{{post.thumbnail.url}}" class="card-img-bottom" style="max-height: 400x;max-width:600px">
                {% endif %}
            </div>
            <div class="card-footer bg-transparent border-success">
                <p class="card-text">Posted On : <small class="text-muted">{{post.created_date}}</small></p>
            </div> 
        </div>
        <br><br>
    {% endfor %}

    {% if not user.is_authenticated %}
        <div class="card text-center">
            <div class="card-body">
            <h5 class="card-title">Login to your account to Publish a Post</h5>
            <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
            <br>
            <p class="card-text">Or</p>
            <a href="{% url 'accounts:signup' %}" class="btn btn-primary">Sign Up</a>
            </div>
        </div>
    {% else %}
    <div class="card text-center">
        <div class="card-body">
        <h5 class="card-title">Create New Post</h5>
        <a href="{% url 'blog:create_post' %}" class="btn btn-primary">New Post</a>
        <br>
        <!-- <p class="card-text">Or</p>
        <a href="{% url 'accounts:signup' %}" class="btn btn-primary">Sign Up</a>
        </div> -->
    </div>
    {% endif %}

{% endblock %}